language: python
sudo: false
cache: pip
dist: trusty

matrix:
  fast_finish: true

install:
  - "pip install --upgrade pip pipenv"
  - "pipenv install --dev"
script:
    - "pipenv run pytest -v -n auto tests/"

jobs:
  include:
    - stage: test
    - python: "3.7"
      dist: xenial
      sudo: required
    - python: "3.6"
    - python: "2.7"
    - python: "3.5"
    - python: "3.4"
    - stage: packaging
      python: "3.6"
      install:
        - "pip install --upgrade check-manifest readme-renderer"
      script:
        - "python setup.py check -m -r -s"
    - stage: coverage
      python: "3.6"
      install:
        - "pip install --upgrade pip pipenv"
        - "pipenv install --dev"
      script:
        - "pipenv run pytest -n auto --timeout 300 --cov=vistir --cov-report=term-missing --cov-report=xml --cov-report=html tests"
