environment:
  matrix:
    # Unit and integration tests.
    - PYTHON: "C:\\Python27"
      RUN_INTEGRATION_TESTS: "True"
    - PYTHON: "C:\\Python36-x64"
      RUN_INTEGRATION_TESTS: "True"
    # Unit tests only.
    - PYTHON: "C:\\Python27-x64"
    - PYTHON: "C:\\Python34-x64"
    - PYTHON: "C:\\Python35-x64"

install:
  - "SET PATH=%PYTHON%\\;%PYTHON%\\Scripts;%PATH%"
  - "python --version"
  - "python -m pip install --upgrade pip pipenv pytest pytest-timeout pytest-cov"
  - "python -m pipenv install --dev"
  - "python -m pipenv run pip install --upgrade -e .[tests,spinner]"

build: off

test_script:
  # Shorten paths, workaround https://bugs.python.org/issue18199
  - "subst T: %TEMP%"
  - "set TEMP=T:\\"
  - "set TMP=T:\\"
  - "python -m pipenv run pytest -ra tests"
